@startuml
'https://plantuml.com/class-diagram



Factory <|-ConcreteFactory
Product <|-ConcreteProduct

ConcreteFactory ...>ConcreteProduct

abstract class Factory {
+ abstract Product createProduct()
}
class ConcreteFactory {
}
abstract class Product {
+ abstract void method()
}
class ConcreteProduct {
}

@enduml